---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visign-web
spec:
  template:
    spec:
      containers:
        - name: visign-web
          image: visignnonprodacrzse7xf.azurecr.io/visign-web:dev-1c9ea70c138983b1b2267eca5dedca8178fa349b
---
apiVersion: batch/v1
kind: Job
metadata:
  name: visign-db-migration
spec:
  template:
    spec:
      containers:
        - name: migration
          image: visignnonprodacrzse7xf.azurecr.io/visign-web-migrator:dev-1c9ea70c138983b1b2267eca5dedca8178fa349b
