apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: visign-kv-secrets
spec:
  parameters:
    userAssignedIdentityID: "0b0c336b-36fd-4fe8-b12e-e7671d4ea799"
    keyvaultName: "visign-prod-kv-vnktt4"