---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visign-web
spec:
  template:
    spec:
      containers:
        - name: visign-web
          image: visignprodacrvnktt4.azurecr.io/visign-web:main-6ed7c178fd8ad642325371d376c07e16bcf8349b
---
apiVersion: batch/v1
kind: Job
metadata:
  name: visign-db-migration
spec:
  template:
    spec:
      containers:
        - name: migration
          image: visignprodacrvnktt4.azurecr.io/visign-web-migrator:main-6ed7c178fd8ad642325371d376c07e16bcf8349b
