---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visign-ai
spec:
  template:
    spec:
      containers:
        - name: visign-ai
          image: visignnonprodacrzse7xf.azurecr.io/visign-ai:dev-72f864057f503cd9ecd45931ce5c01cb4bab75b8
