---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visign-ai
spec:
  template:
    spec:
      containers:
        - name: visign-ai
          image: visignnonprodacrzse7xf.azurecr.io/visign-ai:dev-1c9ea70c138983b1b2267eca5dedca8178fa349b
