---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visign-ai
spec:
  template:
    spec:
      containers:
        - name: visign-ai
          image: visignprodacrvnktt4.azurecr.io/visign-ai:main-6ed7c178fd8ad642325371d376c07e16bcf8349b
