---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visign-ai
spec:
  template:
    spec:
      containers:
        - name: visign-ai
          image: visignnonprodacrzse7xf.azurecr.io/visign-ai:dev-817602b7d53f9cfcd311964bcc9def9e83b4cbcf