- op: replace
  path: /spec/rules/0/host
  value: qa.lyhua.dpdns.org
- op: replace
  path: /spec/tls/0/hosts/0
  value: qa.lyhua.dpdns.org
- op: replace
  path: /spec/tls/0/secretName
  value: visign-tls-qa