apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: visign-kv-secrets
spec:
  parameters:
    userAssignedIdentityID: "37bbc685-c4f0-4274-bc54-9422ec00d254"
    keyvaultName: "visign-nonprod-kv-zse7xf"