apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: visign-kv-secrets
spec:
  parameters:
    userAssignedIdentityID: "ac5d34e7-0ff4-4060-aa9d-89b06821eed9"
    keyvaultName: "visign-nonprod-kv-zse7xf"