---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visign-web
spec:
  template:
    spec:
      containers:
        - name: visign-web
          image: visignnonprodacrzse7xf.azurecr.io/visign-web:qa-72f864057f503cd9ecd45931ce5c01cb4bab75b8 # we are suppose to use seperate container registries but this will do for now
---
apiVersion: batch/v1
kind: Job
metadata:
  name: visign-db-migration
spec:
  template:
    spec:
      containers:
        - name: migration
          image: visignnonprodacrzse7xf.azurecr.io/visign-web-migrator:qa-72f864057f503cd9ecd45931ce5c01cb4bab75b8
